### ISSUE TITLE
Search Template

### ISSUE THREAD

**Issue by patrickwelker** [stephennancekivell/searchbrew#1]
The live updates are pretty cool, but most times I prefer to search via a launcher like LaunchBar or Alfred; hence my question: is there a a search template like `http://searchbrew.com/search/speedtest` or `http://searchbrew.com/?search=speedtest`?

**Comment by stephennancekivell** [comment]
Im not sure what you mean by a search template. I havent used Alfred. But the url for the json data is `http://searchbrew.com/search?q=cake` You can see this in your browsers dev tools.

Hope that helps.

**Comment by patrickwelker** [comment]
I wasn't exactly sure how to describe it, but a parameter than can be added to the URL string and opens up `searchbrew.com` with the result.

Something like the http://braumeister.org/formula/imagemagick or http://brewformulas.org/search?utf8=%E2%9C%93&search%5Bterm%5D=imagemagick&commit=Search. I prefer the minimalism and live updated search of searchbrew and would like to access it via an URL scheme, too.

Maybe I can build something for LaunchBar. I let you know.
