### ISSUE TITLE
allow query parameter in URL

### ISSUE THREAD

**Issue by MareoRaft** [stephennancekivell/searchbrew#4]
It would be great if your webserver caught URL parameters.  That way a URL like

```
http://searchbrew.com/?query=mips
```

Could open the webpage and immediately search for "mips".  This would be a great convenience because it would allow people to write scripts that open up your webpage on a particular search.

This would not be difficult to add either.  Thanks for considering this feature request!

**Comment by kleerkoat** [comment]
this would be really nice!

**Comment by stephennancekivell** [comment]
Hi guys, thanks for your interest. I've added it to work like this. The `#` is required because of angular.

`http://searchbrew.com/#?q=mips`


Added in commit https://github.com/stephennancekivell/searchbrew/commit/b619fcc6f94335b4bdc2d40c2a75f148bd6de374

**Comment by MareoRaft** [comment]
Thanks for listening!  Works great!
